Module4
sujitn/DevOps-Course-Exercise pull request #2
Opened 2020-08-25 15:35 UTC by sujitn

2020-08-27 16:43 UTC, hugh-emerson requested changes
You've made some progress but haven't finished the exercise yet. Can you please try again. The aim is to reach the point where `vagrant up` will start the VM and trigger the app to start up such that you can use the app via localhost:5000 on the host machine. See my comments for some suggestions

You should also update the README to mention vagrant.

Re-submit when you have managed that, or let us know if you are stuck.

Also, your module 3 work has not been approved in Aptem yet, please re-submit it if you believe you've completed the module 3 exercise.

2020-08-27 16:43 UTC, hugh-emerson commented on pyproject.toml
> +Werkzeug==1.0.1
Biggest issue is that this file does not work. It looks like you've just copied from your requirements.txt file, which means the formatting is wrong and `poetry install` will fail. Have you tried running `poetry install`?

Also, you shouldn't include nested dependencies, just the ones that you explicitly need for your app. So python, flask, requests, python-dotenv and maybe a few more that you added to your project. It looks like you may have added some unnecessary dependencies to your project in your Module3 merge... but that's a discussion for your module 3 changes.

2020-08-27 16:43 UTC, hugh-emerson commented on Vagrantfile
> +	eval "$(pyenv virtualenv-init -)"
You presumably found that these lines necessary after trying source ~/.bashrc didn't work.

Vagrant's .bashrc exits early if you're in a non-interactive shell (you can look for it and read it if you `vagrant ssh`)
You should be appending to `.profile` instead. Then when you `source ~/.profile` you won't need to repeat yourself like this.
And then it will also get loaded for your other script that tries to launch the app

2020-08-27 16:43 UTC, hugh-emerson commented on Vagrantfile
> +  #   apt-get install -y apache2
Remove commented out line

2020-08-27 16:43 UTC, hugh-emerson commented on Vagrantfile
> +		poetry run flask run
You haven't said anything on this PR or in Aptem, but have you tried running this Vagrantfile? What happens when you run vagrant up?

I expect this to currently fail for a few reasons, starting with the fact you are in the wrong directory.

2020-08-27 16:43 UTC, hugh-emerson commented on Vagrantfile
> +  # Disable automatic box update checking. If you disable this, then
You can remove all of these comments once you have the Vagrantfile set up. Your codebase is not the correct place to store general Vagrant docs.

2020-08-27 19:22 UTC, sujitn commented on pyproject.toml
> +Werkzeug==1.0.1
had the wrong commits, this is fixed

2020-09-04 16:38 UTC, hugh-emerson approved these changes
Looks good. I've left some suggestions but go ahead and merge when you're ready.

You should also mention vagrant in the README as an option for running the app

2020-09-04 16:38 UTC, hugh-emerson commented on pyproject.toml
> +[tool.poetry]
The exercise brief didn't explain this, but you could try moving to poetry entirely and stop using pip/setup.sh.

If you install poetry on your machine, you should be able to run `poetry install` and `poetry run flask run`
Then you don't need to have both requirements.txt and pyproject.toml

If you make that change, don't forget to update the README.

Also, you will need to add test dependencies to this file, like pytest. They should go under the section `[tool.poetry.dev-dependencies]`

2020-09-04 16:38 UTC, hugh-emerson commented on Vagrantfile
> +	eval "$(pyenv virtualenv-init -)"
You shouldn't need to repeat these three lines now that you are updating ~/.profile and running `source ~/.profile`

2020-09-04 16:38 UTC, hugh-emerson commented on Vagrantfile
> +      poetry run flask run --host 0.0.0.0
This works as much as the exercise brief asked for but you may have noticed it means `vagrant up` doesn't complete and then vagrant manager gets confused and you can't easily run e.g. `vagrant halt` afterwards

You should run the web app as a background process. E.g. 
`nohup poetry run flask run --host 0.0.0.0 > logs.txt 2>&1 &` where `nohup ... &` means to run the command as a separate process. `> logs.txt 2>&1` is to save the output to a file.

2020-09-28 07:59 UTC, merged